dictionaries:
    # brand:
    #     parentPosTag: 'nt 1'
    #     list:
    # product:
    #     parentPosTag: 'nm 1'
    #     list:
    keyword:
        parentPosTag: ''
        list:
            - 'YSM-brand.txt'
            - 'YSM-product.txt'
            - 'hot-keyword.txt'
            - 'iaskTags.txt'
            - 'keyword-from-api.txt'
    nf:
        parentPosTag: ''
        list:
            - 'foods_ch.sc.dic'
            - 'foods_speceial_tw.sc.dic'
            - 'foods_tw.sc.dic'
