dictionaries:
    keyword:
        parentPosTag: ''
        list:
            - 'keyword-from-api.txt'
    nf:
        parentPosTag: ''
        list:
            - 'foods_ch.sc.dic'
            - 'foods_speceial_tw.sc.dic'
            - 'foods_tw.sc.dic'
